#Free Palestine <3
#Free Ukraine <3


# GreetMe is the best server plugin for greeting your players!
# Make every arrival feel welcomed by greeting them with a customized greeting and wonderful effect!
# This plugin does fully support PlaceholderAPI, Make sure that you ran the command "/papi ecloud download player"


# Messages:

# You can change the greeting message from here (This message will only be sent to the player)
greeting-message: "#E7E7E7&l[!] &#fb5e10&lW&#fb5816&le&#fb531c&ll&#fb4d21&lc&#fb4827&lo&#fc422d&lm&#fc3d33&le &#fc3738&lt&#fc323e&lo &#fc2c44&lt&#fc274a&lh&#fc214f&le &#fc1c55&ls&#fd165b&le&#fd1161&lr&#fd0b66&lv&#fd066c&le&#fd0072&lr %player_name%!"

# You can change the greeting broadcast message from here (This message will be sent to all online players on the server)
greeting-broadcast: "#E7E7E7&l[!] &#fb5e10&lE&#fb5915&lv&#fb551a&le&#fb501f&lr&#fb4b24&ly&#fc4729&lo&#fc422d&ln&#fc3d32&le &#fc3837&lp&#fc343c&ll&#fc2f41&le&#fc2a46&la&#fc264b&ls&#fc2150&le &#fc1c55&lw&#fd185a&le&#fd135e&ll&#fd0e63&lc&#fd0968&lo&#fd056d&lm&#fd0072&le %player_name%!"

# You can change the leaving message from here (This message will be sent to all online players on the server)
leaving-message: "#E7E7E7&l[!] &#fb5e10&l%player_name% h&#fb5817&la&#fb511d&ls &#fb4b24&ll&#fc452a&le&#fc3f31&lf&#fc3837&lt &#fc323e&lt&#fc2c44&lh&#fc264b&le &#fc1f51&ls&#fc1958&le&#fd135e&lr&#fd0d65&lv&#fd066b&le&#fd0072&lr"


# Options:

JoinFirework: true
JoinSound: true
JoinTitle: true


# Titles

Greeting-Title: "&#fb5e10&lW&#fb5915&le&#fb541a&ll&#fb4f1f&lc&#fb4a25&lo&#fc452a&lm&#fc402f&le &#fc3b34&lt&#fc3639&lo &#fc313e&lt&#fc2d44&lh&#fc2849&le &#fc234e&lF&#fc1e53&lu&#fc1958&ln &#fd145d&lZ&#fd0f63&lo&#fd0a68&ln&#fd056d&le&#fd0072&l!"
Greeting-SubTitle: "&#fb5e10&lR&#fb5618&le&#fb4e20&ll&#fc4729&la&#fc3f31&lx &#fc3739&la&#fc2f41&ln&#fc2749&ld &#fc1f51&lE&#fd185a&ln&#fd1062&lj&#fd086a&lo&#fd0072&ly"

FadeIn: 10
Stay: 70
FadeOut: 20


# Sounds:

# You can edit the join sound from here, you can find sounds name from this page https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
# If you want to disable it, leave it blank.
join-sound: "ITEM_GOAT_HORN_SOUND_0"

sound-volume: "1"
sound-pitch: "1"



# This plugin was made by YoyoDevs!
# This is version 2.0. please report any bugs to my discord iiYoyo#2455.